### ISSUE TITLE
Issuer failed to take the value of XML KeyName

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-android#165]
Notice that `TokenDefinition.getKeyName()` was there for a while but we couldn't connect that to the UI.

![screenshot_20180520-234431](https://user-images.githubusercontent.com/548435/40280943-3c8bab5e-5c8d-11e8-8805-b3f87864976b.gif)

**Comment by JamesSmartCell** [comment]
Asset issuer is read from XML. Behaviour is now correct.
