### ISSUE TITLE
Encapsulation needed to avoid multiple pieces of code doing the same thing

### ISSUE THREAD

**Issue by colourful-land** [alpha-wallet/alpha-wallet-android#177]
SendActivity.java :

        symbolText.setText(TextUtils.isEmpty(token.tokenInfo.name)
                ? token.tokenInfo.symbol.toUpperCase()
                : getString(R.string.token_name, token.tokenInfo.name, token.tokenInfo.symbol.toUpperCase()));

ChangeTokenHolder.java :

        if (TextUtils.isEmpty(token.tokenInfo.name)) {
            symbol.setText(token.tokenInfo.symbol);
        } else {
            symbol.setText(token.tokenInfo.name + " (" + token.tokenInfo.symbol + ")");
        }

TokenHolder.java :

            symbol.setText(TextUtils.isEmpty(token.tokenInfo.name)
                        ? token.tokenInfo.symbol.toUpperCase()
                        : token.getFullName());// getString(R.string.token_name, token.tokenInfo.name, token.tokenInfo.symbol.toUpperCase()));

**Comment by JamesSmartCell** [comment]
Has had a few passes to remove duplication. Now most views are updated in one place.
