### ISSUE TITLE
redemption QR code Page should show more ticket details on asset card, not only 1 Voucher

### ISSUE THREAD

**Issue by zhangzhongnan928** [alpha-wallet/alpha-wallet-android#201]
![image 2018-05-25 11 03 33](https://user-images.githubusercontent.com/33795543/40524117-45b79d06-600b-11e8-910a-8c40642fe57e.jpg)

Eg. 
For FIFA tickets should be "1 FIFA WC2018 Vouchers" instead of "1 Vouchers"

**Comment by JamesSmartCell** [comment]
fixed
