### ISSUE TITLE
Detect if a new version is available

### ISSUE THREAD

**Issue by colourful-land** [alpha-wallet/alpha-wallet-android#280]
@zhangzhongnan928  recently focused our marketing and pr activities in China - because our international girl Ariel are just reporting to work as now. For the China market the Android app is installed by user downloading the apk. We need this functionality urgently as we are accumulating apk file based users.

- Everytime the app launches, it checks if it is installed through Google Play Store.
- If it is not installed from Google Play Store, access http://awallet.io/apk - note that for now the website is slow enough to be considered blocked in China so we might change it - and check if a new version is available.
- Prompt the user of the new version (notification?) with direct download link.

(P. S. be designful - e.g. Prompt "a major update is available" as well as "a bugfix release is available" etc)

If the first step is not possible (check if the app itself is installed through Google Play Store), then the ideal solution is to configure Gradle to produce different apk files for Google and for Chinese users - I studied this before, so tag me if you want to go with that.

**Comment by JamesSmartCell** [comment]
Seems to be working correctly now. Will close.
