### ISSUE TITLE
XML generation needs to be sent to us

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-android#293]
On completion of the xml desktop process, we need to be able to get their XML which contains their contract address so we can add it to the repo server

**Comment by hboon** [comment]
One way:

1) maintain a git repo (locally or on server. This needs to pull to get updates.)
2) commit to it programmatically (through a git lib or run shell commands)
3) push to GitHub
4) then use the GitHub API to create a PR, with the commit ID/hash, title, body, etc

This is similar to what we do when we create a PR manually: (1), (2), (3) is what we normally do on our development machines via shell, (4) is what we do in the browser.

git credentials involved, maybe server-side might be better? Can create a GitHub "bot" account for this. Nothing special, just a dedicated account for this purpose.

**Comment by James-Sangalli** [comment]
@hboon good point, can use a git bot that has an access token restricted to submitting PR's

**Comment by James-Sangalli** [comment]
@hboon @colourful-land this could be even simplier tho, simply send us an email and we review and copy it over directly. Probably can go on like that for a while

**Comment by colourful-land** [comment]
@lyhistory can you allow Issues feature on your repository https://github.com/lyhistory/peter-s-tool - I feel this discussion belong there.

**Comment by lyhistory** [comment]
@colourful-land done, and Sanglli said I misunderstood, I have changed the repository name back to https://github.com/lyhistory/alpha-wallet-android, and later I will rename 'desktop' folder to 'peters tool desktop'

**Comment by colourful-land** [comment]
@lyhistory Please change the repo name back. I want to direct users to download Peter's Tool from your repo's RELEASE tab. It will be too confusing if the users go to a repo called alpha-wallet and download Peter's Tool from its release tab. They will think they are downloading AlphaWallet. Sangalli is aware of this intention.

**Comment by lyhistory** [comment]
@colourful-land done, changed it back

**Comment by colourful-land** [comment]
@hboon  finally I can close this issue, please file your improvement suggestion here:

https://github.com/lyhistory/Peter-s-Tool/issues

Search "One Way" on this page for your suggestion:
