### ISSUE TITLE
dmz website is incorrectly displaying unavailable

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-android#325]
To reproduce,

1) open a magic link for blockchain events
2) notice it is red when it shouldn't be
3) refresh it a couple of times and it will go to green.

Seems something is wrong with the server

**Comment by hboon** [comment]
I get `unavailable` when it's red. Looks like there's only 1 line which does that and it's in a `catch` handler. Maybe someone can add a log to see what's that exception and stacktrace?

**Comment by JamesSmartCell** [comment]
Please send me a broken link, I'm unable to reproduce the problem. When I generate links they work correctly on the website.

**Comment by James-Sangalli** [comment]
https://app.awallet.io/AAAAAFxORgCDDhZQqHp1TjfKftdrcAOVp8YWFICZIUHgFR0DJGCz8WENnKlX_1MNrOXDXmFR8dLvJhbb8g9e2oLhLi9tliU44J4huN5DPR66LX19uanvtOlJn8LTShs=

**Comment by James-Sangalli** [comment]
@JamesSmartCell seems like this is related to infura speeds?

**Comment by James-Sangalli** [comment]
Seems the cause was Infura being down, we will mitigate this in future by having our own node and switching to infura as a backup
