### ISSUE TITLE
DApp browser defaults to xcontract 

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-android#328]
![screenshot_20180913-141807_alphawallet](https://user-images.githubusercontent.com/16630514/45471820-d8665d80-b764-11e8-9b97-fa2306e64f7a.jpg)

**Comment by James-Sangalli** [comment]
@JamesSmartCell i changed website to google and restarted the app. it defaulted to xcontract. This is using the latest release from the playstore

**Comment by JamesSmartCell** [comment]
Unable to reproduce.

Latest install from play store on all Android phones in office takes you to State of the DApps.

**Comment by James-Sangalli** [comment]
Appears you are right, for some reason my app won't update when I go to the playstore...
